name: HealingTotem
main: com.github.tprk77.healingtotem.HTPlugin
version: ${project.version}
author: tprk77, Rehv
description: Health Regeneration from Totem Poles!
permissions:
  healingtotem.*:
    description: Gives access to all common HealingTotem permissions
    children:
      healingtotem.build: true
      healingtotem.break: true
      healingtotem.heal: true
      healingtotem.damage: true
  healingtotem.build:
    description: Allows user to build totems
    default: true
  healingtotem.break:
    description: Allows user to break totems
    default: true
  healingtotem.heal:
    description: Allows user to be healed by totems
    default: true
  healingtotem.damage:
    description: Allows user to be damaged by totems
    default: true
  healingtotem.unlimitedbuild:
    description: Allows user to build an unlimited number of totems
    default: op
